[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "^/(venv|.venv|.git|dist|build|.mypy_cache|.ruff_cache|.pytest_cache)/"

[tool.isort]
profile = "black"
py_version = 311
line_length = 100
known_first_party = ["app"]
src_paths = ["app"]
combine_as_imports = true
force_sort_within_sections = true
skip_gitignore = true

[tool.ruff]
target-version = "py311"
line-length = 100
src = ["app"]
exclude = [
  ".git",
  "venv",
  ".venv",
  "build",
  "dist",
  ".mypy_cache",
  ".pytest_cache",
  ".ruff_cache",
]

[tool.ruff.lint.isort]
known-first-party = ["app"]
force-sort-within-sections = true

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "PL", "RUF"]
ignore = [
  "E203",  # whitespace before ':' (black compatibility)
  "E501",  # line length (handled by formatter)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["."]
asyncio_mode = "auto"
